version: "3.7"

services:
  entregas-db:
    image: postgres
    container_name: entregas-db
    restart: always
    tty: true
    ports:
      - 5432:5432
    networks:
      - entregas-network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=entregas
  entregas-api:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: entregas-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - entregas-network
networks:
  entregas-network:
    driver: bridge
